name: 🐞 Bug Report
description: Report an issue with the project.
title: ""  # Removed "[Bug]:" from the title
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "### Please provide details below 👇"

  - type: input
    id: system
    attributes:
      label: "Operating System"
      description: "Which OS are you using?"
      placeholder: "Windows 11, macOS Ventura..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "How severe is this bug?"
      options:
        - "🚨 Select severity (required)"
        - "🔴 Severity: Critical"
        - "🟠 Severity: High"
        - "🟡 Severity: Medium"
        - "🔵 Severity: Low"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Describe the issue"
      description: "What happened? Provide steps to reproduce."
      placeholder: "Steps to reproduce the bug..."
    validations:
      required: true
