name: 🐞 Bug Report
description: Report an issue with the project.
title: "- "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "### Please provide details below 👇"

  - type: input
    id: system
    attributes:
      label: "Operating System"
      description: "Which OS are you using?"
      placeholder: "Windows 11, macOS Ventura..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "How severe is this bug?"
      options:
        - "🚨 Select severity (required)"
        - "🔴 Critical (System Down, Major Security Issue)"
        - "🟠 High (Major Issue, No Workaround)"
        - "🟡 Medium (Affects Functionality, Workaround Available)"
        - "🔵 Low (Minor UI Issue, No Impact on Functionality)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Describe the issue"
      description: "What happened? Provide steps to reproduce."
      placeholder: |
        **Summary:**
        (Briefly describe the bug)
        
        **Steps to reproduce:**
        1. Login to the platform
        2. Navigate to XYZ
        3. Click on ABC
        
        **Actual Result:**
        (What actually happened?)
        
        **Expected Result:**
        (What should have happened?)
        
        **Screenshots (if applicable):**
        (Attach screenshots to illustrate the issue)
    validations:
      required: true
