name: Auto Comment on Issues
on:
  issues:
    types: [opened]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post Auto-Comment
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "👋 Hi @${{ github.event.issue.user.login }},  
              Thanks for reporting this! We’ve received your bug report and are looking into it.  
              @charles-rollet has been assigned and will follow up with you shortly. 🚀  
              If you have any additional details, feel free to add them here!"
            });
