name: Auto Label Severity
on:
  issues:
    types: [opened]

jobs:
  label-severity:
    runs-on: ubuntu-latest
    steps:
      - name: Add Severity Label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const repo_owner = context.repo.owner;
            const repo_name = context.repo.repo;
            const issue = await github.rest.issues.get({
              owner: repo_owner,
              repo: repo_name,
              issue_number: issue_number
            });

            const body = issue.data.body;

            let severityLabel = null;
            if (body.includes("🔴 Critical")) severityLabel = "Severity: Critical";
            if (body.includes("🟠 High")) severityLabel = "Severity: High";
            if (body.includes("🟡 Medium")) severityLabel = "Severity: Medium";
            if (body.includes("🔵 Low")) severityLabel = "Severity: Low";

            if (severityLabel) {
              await github.rest.issues.addLabels({
                owner: repo_owner,
                repo: repo_name,
                issue_number: issue_number,
                labels: [severityLabel]
              });
            }
